version: '3'

services:
  backend:
    build: .
    ports:
      - '5000:5000'
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
